name: new_clinco

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
    sdk: '>=2.18.1 <3.0.0'


dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    http: any
    flutter_bloc: any
    bloc: any
    fluttertoast: any   
    device_preview: any
    flutter_offline: any
    hexcolor: any 
    cached_network_image: any
    splash_screen_view: any
    url_launcher: any


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0


flutter:
    uses-material-design: true
    assets:
      - assets/images/offline/
      - assets/logo/
